import {initial,order} from './core.js';const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),ids=['noise','density','count','speed','rate','size'];let state,ticks=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,busy=false,worker,timer,last=0,slow=0,delay=0,history=[],scan=null,results=[],runConfig=null;
function msg(s){$('notice').textContent=s;$('notice').hidden=!s;}function cancel(){clearTimeout(timer);worker?.terminate();worker=null;busy=false;}function sync(){for(const k of ids)$(k+'Val').value=$(k).value;$('play').textContent=paused?'再生 / Play':'一時停止 / Pause';$('settings').disabled=!!scan;$('scan').textContent=scan?'走査を終了 / Stop sweep':'走査を開始 / Start sweep';$('csv').disabled=!results.length;}
function seed(){let s=+$('seed').value;if(!Number.isInteger(s)||s<0||s>4294967295){s=42;$('seed').value=s;}return s;}
function resetState(){cancel();state=initial(+$('count').value,+$('density').value,seed());ticks=0;history=[];slow=0;delay=0;draw();}
function reset(){scan=null;results=[];runConfig=null;resetState();msg('');sync();plotSweep();}
function graph(id,data){const c=$(id),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#344052';x.strokeRect(18,8,c.width-24,c.height-25);x.fillStyle='#929aab';x.font='10px system-ui';x.fillText('1',3,14);x.fillText('0',3,c.height-17);x.strokeStyle='#5ad1c7';x.beginPath();data.forEach(([a,b],i)=>{const px=18+a*(c.width-24),py=8+(1-b)*(c.height-25);i?x.lineTo(px,py):x.moveTo(px,py);});x.stroke();for(const[a,b]of data){x.fillStyle='#5ad1c7';x.fillRect(16+a*(c.width-24),6+(1-b)*(c.height-25),4,4);}}
function plotSweep(){graph('sweepChart',results.map(r=>[r.noise,r.mean]).sort((a,b)=>a[0]-b[0]));}
function draw(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);const side=Math.max(1,Math.min(r.width-24,r.height-155)),ox=(r.width-side)/2,oy=(r.height-side)/2-10,s=+$('size').value;ctx.strokeStyle='#283140';ctx.strokeRect(ox,oy,side,side);for(const[x,y,a]of state.p){const px=ox+x/state.L*side,py=oy+y/state.L*side;ctx.strokeStyle=`hsl(${((a*180/Math.PI)%360+360)%360} 70% 65%)`;ctx.beginPath();ctx.moveTo(px-Math.cos(a)*s,py-Math.sin(a)*s);ctx.lineTo(px+Math.cos(a)*s,py+Math.sin(a)*s);ctx.lineTo(px+Math.cos(a+2.5)*s*.6,py+Math.sin(a+2.5)*s*.6);ctx.stroke();}const v=order(state.p);$('alignment').textContent=`Φ = ${v.toFixed(3)}`;$('stats').textContent=`${paused?'Paused':'Running'} · N=${state.p.length} · Step ${ticks}`;graph('chart',history.map((v,i)=>[i/Math.max(1,history.length-1),v]));}
function sweepStep(v){if(!scan)return;scan.steps++;if(scan.steps>200)scan.values.push(v);$('scanStatus').textContent=`η=${(1-scan.index/10).toFixed(1)} · ${scan.steps}/400 · ${scan.index+1}/11`;if(scan.steps===400){const mean=scan.values.reduce((s,x)=>s+x,0)/200,sd=Math.sqrt(scan.values.reduce((s,x)=>s+(x-mean)**2,0)/200);results.push({noise:1-scan.index/10,mean,sd});plotSweep();scan.index++;if(scan.index===11){scan=null;paused=true;$('scanStatus').textContent='走査完了 / Sweep complete';sync();}else{scan.steps=0;scan.values=[];$('noise').value=1-scan.index/10;resetState();sync();}}}
function request(){if(busy||document.hidden)return;busy=true;if(!worker){worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>{paused=true;cancel();msg('計算エラー / Worker error');sync();};worker.onmessage=({data:d})=>{clearTimeout(timer);busy=false;if(d.error){paused=true;cancel();msg(d.error);sync();return;}state=d.state;ticks++;history.push(d.order);if(history.length>300)history.shift();slow=d.ms>60?slow+d.ms:Math.max(0,slow-30);delay=d.ms>30?Math.min(1000,d.ms*2):0;sweepStep(d.order);if(slow>2500){paused=true;cancel();msg('高負荷で停止 / High load; reduce particle count after stopping sweep.');sync();}draw();};}timer=setTimeout(()=>{paused=true;cancel();msg('応答待ち時間超過 / Calculation timeout');sync();},2000);worker.postMessage({state,noise:+$('noise').value,speed:+$('speed').value});}
function frame(t){if(!paused&&!busy&&!document.hidden&&t-last>=Math.max(1000/+$('rate').value,delay)){last=t;request();}requestAnimationFrame(frame);}
$('play').onclick=()=>{paused=!paused;cancel();slow=0;msg('');sync();draw();};$('step').onclick=()=>{paused=true;cancel();sync();request();};$('reset').onclick=reset;for(const k of ids)$(k).addEventListener(['count','density'].includes(k)?'change':'input',()=>{cancel();if(['count','density'].includes(k))reset();else if(['noise','speed'].includes(k))history=[];sync();draw();});
$('scan').onclick=()=>{cancel();if(scan){scan=null;paused=true;$('scanStatus').textContent='走査を終了しました / Sweep stopped';}else{runConfig={count:+$('count').value,density:+$('density').value,speed:+$('speed').value,seed:seed()};scan={index:0,steps:0,values:[]};results=[];$('noise').value=1;paused=false;resetState();plotSweep();msg('');}sync();};
$('csv').onclick=()=>{if(!runConfig||!results.length)return;const text='noise,mean_order,temporal_sd,count,density,speed,seed,warmup_steps,sample_steps\n'+results.map(r=>[r.noise,r.mean,r.sd,runConfig.count,runConfig.density,runConfig.speed,runConfig.seed,200,200].join(',')).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='vicsek-noise-sweep.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('menuToggle').onclick=()=>{const v=$('sidebar').classList.toggle('open');$('sidebarBackdrop').classList.toggle('open',v);$('menuToggle').setAttribute('aria-expanded',v);};$('sidebarBackdrop').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');};addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{cancel();last=0;});reset();requestAnimationFrame(frame);
