import {defaults,initial} from './core.js';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let points=[],params={...defaults},ticks=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,worker,busy=false,timer,last=0,slow=0,interval=0,loadId=0;
const keys=Object.keys(defaults),ids=['count','size','rate',...keys];
function message(s){$('notice').textContent=s;$('notice').hidden=!s;}
function cancel(){clearTimeout(timer);worker?.terminate();worker=null;busy=false;}
function pause(){paused=true;cancel();buttons();}
function buttons(){$('play').textContent=paused?'▶ 再生 / Play':'⏸ 一時停止 / Pause';}
function reset(){cancel();let seed=Number($('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){seed=20;$('seed').value=20;}params={...defaults};for(const k of keys)$(k).value=params[k];points=initial(+$('count').value,seed,$('preset').value);ticks=0;slow=0;interval=0;sync();message('');draw();}
function sync(){for(const id of ids)$(id+'Val').value=$(id).value;buttons();}
function draw(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);if(!points.length)return;let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;for(const [x,y]of points){xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);}const scale=Math.max(.00001,Math.min(Math.max(1,w-48)/Math.max(20,xmax-xmin+4),Math.max(1,h-180)/Math.max(20,ymax-ymin+4)));const cx=(xmin+xmax)/2,cy=(ymin+ymax)/2;for(let i=0;i<points.length;i++){const [x,y]=points[i];ctx.fillStyle=`hsl(${165+65*i/points.length} 65% 65%)`;ctx.beginPath();ctx.arc(w/2+(x-cx)*scale,h/2+(y-cy)*scale,+$('size').value,0,Math.PI*2);ctx.fill();}$('stats').textContent=`${paused?'Paused':'Running'} · N=${points.length} · Step ${ticks}`;}
function request(){if(busy||document.hidden)return;busy=true;if(!worker){worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>{pause();message('計算を停止しました。再生で再試行 / Worker error; press Play to retry.');};worker.onmessage=({data})=>{clearTimeout(timer);busy=false;if(data.error){pause();message(data.error);return;}points=data.points;ticks++;slow=data.ms>60?slow+data.ms:Math.max(0,slow-30);interval=data.ms>30?Math.min(1000,data.ms*2):0;if(slow>2000){pause();message('高負荷で停止。粒子数を減らしてください / High load: reduce particle count.');}draw();};}timer=setTimeout(()=>{pause();message('計算が応答しないため停止 / Calculation timeout');},2000);worker.postMessage({points,params});}
function frame(t){if(!paused&&!document.hidden&&!busy&&t-last>=Math.max(1000/+$('rate').value,interval)){last=t;request();}requestAnimationFrame(frame);}
$('play').onclick=()=>{if(paused){paused=false;slow=0;message('');buttons();}else{pause();draw();}};$('step').onclick=()=>{pause();request();};
$('reset').onclick=reset;$('preset').onchange=reset;$('shuffle').onclick=()=>{$('seed').value=crypto.getRandomValues(new Uint32Array(1))[0];reset();};
for(const id of ids)$(id).addEventListener(id==='count'?'change':'input',()=>{if(id==='count')reset();else{if(keys.includes(id)){cancel();params[id]=+$(id).value;}sync();draw();}});
$('menuToggle').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('sidebarBackdrop').classList.toggle('open',open);$('menuToggle').setAttribute('aria-expanded',open);};$('sidebarBackdrop').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');};
addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{cancel();last=0;});
$('save').onclick=()=>{pause();draw();const data={format:'alife-particle-lenia',version:1,points,params,ticks};const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='particle-lenia-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('保存しました / Saved (paused)');};
async function load(file){const id=++loadId;try{if(!file||file.size>1024*1024)throw Error();const d=JSON.parse(await file.text());if(id!==loadId)return;if(d.format!=='alife-particle-lenia'||d.version!==1||!Array.isArray(d.points)||d.points.length<50||d.points.length>800||!d.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1e6))||!Number.isSafeInteger(d.ticks)||d.ticks<0)throw Error();const p={};for(const k of keys){const v=d.params?.[k];if(typeof v!=='number'||!Number.isFinite(v)||v<+$(k).min||v>+$(k).max)throw Error();p[k]=v;}pause();points=d.points;params=p;ticks=d.ticks;for(const k of keys)$(k).value=p[k];$('count').value=points.length;sync();draw();message('読み込みました。再生で続行 / Loaded; press Play.');}catch{if(id===loadId)message('対応するParticle Lenia JSONではありません。状態は保持 / Invalid file; state retained.');}}
$('open').onclick=()=>$('file').click();$('file').onchange=()=>{load($('file').files[0]);$('file').value='';};addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();if(e.dataTransfer.files.length===1)load(e.dataTransfer.files[0]);else message('ファイルは1つ選択 / Drop one file.');}});
reset();requestAnimationFrame(frame);
