import {defaults,initial,bounds,path,svg} from './core.js';const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),keys=Object.keys(defaults),ids=[...keys,'rate','width'];let state,params={...defaults},ticks=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,worker,busy=false,timer,last=0,slow=0,delay=0;
function msg(s){$('notice').textContent=s;$('notice').hidden=!s;}function cancel(){clearTimeout(timer);worker?.terminate();worker=null;busy=false;}function sync(){for(const k of ids)$(k+'Val').value=$(k).value;$('play').textContent=paused?'再生 / Play':'一時停止 / Pause';}function pause(){paused=true;cancel();sync();}
function render(target,w,h,pad=20){const b=bounds(state.points),s=Math.min((w-pad*2)/b.w,(h-pad*2)/b.h);target.fillStyle='#0b0d12';target.fillRect(0,0,w,h);target.save();target.translate((w-b.w*s)/2-b.x*s,(h-b.h*s)/2-b.y*s);target.scale(s,s);target.strokeStyle='#5ad1c7';target.lineWidth=+$('width').value;target.lineJoin='round';target.lineCap='round';target.stroke(new Path2D(path(state)));target.restore();}
function draw(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.save();ctx.translate(0,45);render(ctx,r.width,Math.max(1,r.height-145),12);ctx.restore();$('stats').textContent=`${paused?'Paused':'Growing'} · Nodes ${state.points.length} / ${params.limit} · Step ${ticks}`;}
function reset(){cancel();let seed=+$('seed').value;if(!Number.isInteger(seed)||seed<0||seed>4294967295){seed=42;$('seed').value=42;}state=initial($('preset').value,seed);ticks=0;slow=0;delay=0;msg('');sync();draw();}
function request(){if(busy||document.hidden)return;if(state.points.length>=params.limit&&params.growth>0){pause();msg('頂点上限に達しました / Node cap reached');draw();return;}busy=true;if(!worker){worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>{pause();msg('計算エラー / Worker error');};worker.onmessage=({data:d})=>{clearTimeout(timer);busy=false;if(d.error){pause();msg(d.error);return;}state=d.state;ticks++;slow=d.ms>60?slow+d.ms:Math.max(0,slow-30);delay=d.ms>30?Math.min(1000,d.ms*2):0;if(slow>2500){pause();msg('高負荷で停止。初期化して上限を下げてください / High load; reset with a lower cap.');}if(state.points.length>=params.limit&&params.growth>0){pause();msg('頂点上限に達しました / Node cap reached');}draw();};}timer=setTimeout(()=>{pause();msg('計算が応答しないため停止 / Calculation timeout');},2000);worker.postMessage({state,params});}
function frame(t){if(!paused&&!busy&&!document.hidden&&t-last>=Math.max(1000/+$('rate').value,delay)){last=t;request();}requestAnimationFrame(frame);}
$('play').onclick=()=>{if(paused){paused=false;slow=0;msg('');sync();}else pause();draw();};$('step').onclick=()=>{pause();request();};$('reset').onclick=reset;$('preset').onchange=reset;for(const k of ids)$(k).oninput=()=>{if(keys.includes(k)){cancel();params[k]=+$(k).value;}sync();draw();};
function download(blob,ext){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='differential-growth-'+ticks+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('svg').onclick=()=>{pause();draw();download(new Blob([svg(state,+$('width').value)],{type:'image/svg+xml'}),'svg');};$('png').onclick=()=>{pause();draw();const b=bounds(state.points),c=document.createElement('canvas'),scale=1600/Math.max(b.w,b.h);c.width=Math.max(1,Math.round(b.w*scale));c.height=Math.max(1,Math.round(b.h*scale));render(c.getContext('2d'),c.width,c.height,0);c.toBlob(blob=>{if(blob)download(blob,'png');else msg('画像保存に失敗しました / Export failed');},'image/png');};
$('menuToggle').onclick=()=>{const v=$('sidebar').classList.toggle('open');$('sidebarBackdrop').classList.toggle('open',v);$('menuToggle').setAttribute('aria-expanded',v);};$('sidebarBackdrop').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');};addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{cancel();last=0;});reset();requestAnimationFrame(frame);
