import {createCA} from './ca.js';
const $=id=>document.getElementById(id),canvas=$('canvas');
const gl=canvas.getContext('webgl',{alpha:false,preserveDrawingBuffer:true,antialias:false});
let ca=null,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,loading=true,failed=false,lost=false,request=0,abort=null,last=0,credit=0,target=null;
const cache=new Map(),actions=['play','step','reset','grow','clear','save'];
const hints={1:'成長を学習。長時間の形の維持や修復は保証されません。 / Trained to grow; persistence and repair are not guaranteed.',2:'形の維持を学習。一部のモデルは修復もできます。 / Trained to persist; some models can also repair damage.',3:'損傷を受ける学習で、自己修復能力を獲得したモデル。大きすぎる損傷は修復できない場合があります。 / Trained with damage; excessive damage may still prevent recovery.'};
function controls(){for(const id of actions)$(id).disabled=loading||failed||lost||!ca;$('play').textContent=paused?'▶ 再生 / Play':'⏸ 一時停止 / Pause';}
function pause(value){paused=value;credit=0;if(value)target=null;controls();}
function draw(){if(!ca||lost)return;twgl.bindFramebufferInfo(gl);ca.draw($('view').value);$('stats').textContent=`${ca.getStepCount().toLocaleString()} steps · 96 × 96 cells${target!==null?' · 早送り / Advancing…':''}`;}
async function load(){const id=++request;abort?.abort();abort=new AbortController();loading=true;failed=false;target=null;credit=0;controls();$('retry').hidden=true;$('notice').textContent='読み込み中 / Loading…';$('modelHint').textContent=hints[$('training').value];const key=`${$('pattern').value}-${$('training').value}`;
  try{if(!gl||lost)throw Error('WebGL');let weights=cache.get(key);if(!weights){const r=await fetch(`models/${key}.json`,{signal:abort.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);weights=await r.json();if(weights.length!==2||weights[0].in_ch!==48||weights[0].out_ch!==128||weights[1].in_ch!==128||weights[1].out_ch!==16)throw Error('Invalid model');cache.set(key,weights);}if(id!==request)return;if(ca){ca.setWeights(weights);ca.reset();}else ca=createCA(gl,weights,[96,96]);ca.setAngle(Number($('rotation').value));$('notice').textContent='';loading=false;controls();draw();}
  catch(e){if(id!==request||e.name==='AbortError')return;loading=false;failed=true;controls();$('notice').textContent=!gl||lost?'この端末ではWebGLを利用できません。対応ブラウザで開き直してください。 / WebGL unavailable; try another browser.':'モデルを読み込めませんでした。再読み込みしてください。 / Model loading failed; please retry.';$('retry').hidden=!gl||lost;$('stats').textContent='停止中 / Unavailable';}
}
$('pattern').onchange=$('training').onchange=load;$('retry').onclick=load;
$('play').onclick=()=>pause(!paused);$('step').onclick=()=>{pause(true);ca.step();draw();};$('reset').onclick=()=>{target=null;credit=0;ca.reset();draw();};$('grow').onclick=()=>{target=ca.getStepCount()+200;paused=false;credit=0;controls();};$('clear').onclick=()=>{pause(true);ca.paint(0,0,10000,'clear');draw();};
$('brush').oninput=()=>{$('brushValue').textContent=$('brush').value;};$('rotation').oninput=()=>{$('rotationValue').textContent=$('rotation').value;if(ca&&!lost){ca.setAngle(Number($('rotation').value));draw();}};$('view').onchange=draw;
let drawing=false,lastPoint=null;
function paint(e){if(!ca||loading||failed||lost)return;const r=canvas.getBoundingClientRect();const x=Math.max(0,Math.min(95,Math.floor((e.clientX-r.left)/r.width*96))),y=Math.max(0,Math.min(95,Math.floor((e.clientY-r.top)/r.height*96)));const seed=$('tool').value==='seed';if(seed&&lastPoint&&Math.hypot(x-lastPoint.x,y-lastPoint.y)<8)return;ca.paint(x,y,seed?1:Number($('brush').value),seed?'seed':'clear');lastPoint={x,y};draw();}
canvas.onpointerdown=e=>{if(e.button!==0)return;drawing=true;lastPoint=null;canvas.setPointerCapture(e.pointerId);paint(e);};canvas.onpointermove=e=>{if(drawing)paint(e);};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;lastPoint=null;};
$('save').onclick=()=>{draw();canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nca-${$('pattern').value}-${ca.getStepCount()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
function menu(open){$('sidebar').classList.toggle('open',open);$('sidebarBackdrop').classList.toggle('open',open);$('menuToggle').setAttribute('aria-expanded',String(open));$('sidebar').inert=matchMedia('(max-width:760px)').matches&&!open;}$('menuToggle').onclick=()=>menu(!$('sidebar').classList.contains('open'));$('sidebarBackdrop').onclick=()=>menu(false);window.addEventListener('keydown',e=>{if(e.key==='Escape'){menu(false);$('menuToggle').focus();}});window.addEventListener('resize',()=>menu(false));
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;pause(true);$('notice').textContent='描画が中断されました。ページを再読み込みしてください。 / Graphics context lost; reload the page.';});
document.addEventListener('visibilitychange',()=>{last=0;credit=0;});
function frame(t){const dt=last?Math.min(.1,(t-last)/1000):0;last=t;if(ca&&!loading&&!failed&&!lost&&!paused&&!document.hidden){credit=Math.min(2,credit+dt*Number($('speed').value));const steps=target===null?Math.floor(credit):2;for(let i=0;i<steps;i++){ca.step();if(target!==null&&ca.getStepCount()>=target){pause(true);break;}}if(target===null)credit=Math.max(0,credit-steps);draw();}requestAnimationFrame(frame);}
menu(false);load();requestAnimationFrame(frame);
