import {defaults,initial} from './core.js';
const $=id=>document.getElementById(id),c=$('canvas'),ctx=c.getContext('2d'),buffer=document.createElement('canvas'),bc=buffer.getContext('2d');
const keys=Object.keys(defaults),ids=[...keys,'rate','brush'];let n=128,a,p={...defaults},ticks=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,worker,busy=false,timer,last=0,slow=0,delay=0,drag=false,erase=false,view,loadId=0;
function message(s){$('notice').textContent=s;$('notice').hidden=!s;}
function cancel(){clearTimeout(timer);worker?.terminate();worker=null;busy=false;}
function sync(){for(const k of ids)$(k+'Val').value=$(k).value;$('dt').disabled=$('mode').value==='discrete';$('play').textContent=paused?'▶ 再生 / Play':'⏸ 一時停止 / Pause';}
function pause(){paused=true;cancel();sync();}
function reset(){cancel();n=+$('resolution').value;let seed=+$('seed').value;if(!Number.isInteger(seed)||seed<0||seed>4294967295){seed=42;$('seed').value=42;}a=initial(n,seed,$('preset').value);ticks=0;slow=0;delay=0;message('');sync();draw();}
function draw(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);const side=Math.max(1,Math.min(r.width-24,r.height-155));view={x:(r.width-side)/2,y:(r.height-side)/2-15,size:side};buffer.width=buffer.height=n;const img=bc.createImageData(n,n);let mass=0;for(let i=0;i<a.length;i++){const v=a[i];mass+=v;img.data[i*4]=8+v*140;img.data[i*4+1]=12+v*226;img.data[i*4+2]=18+v*202;img.data[i*4+3]=255;}bc.putImageData(img,0,0);ctx.imageSmoothingEnabled=true;ctx.drawImage(buffer,view.x,view.y,side,side);$('stats').textContent=`${paused?'Paused':'Running'} · ${n}² · Step ${ticks} · ${(100*mass/a.length).toFixed(1)}%`;}
function request(){if(busy||document.hidden||drag)return;if(p.b1>=p.b2||p.d1>=p.d2){pause();message('下限は上限より小さくしてください / Invalid thresholds');return;}busy=true;if(!worker){worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>{pause();message('計算エラー / Worker error. 再生で再試行 / Play to retry');};worker.onmessage=({data:d})=>{clearTimeout(timer);busy=false;if(d.error){pause();message(d.error);return;}a=d.a;ticks++;slow=d.ms>80?slow+d.ms:Math.max(0,slow-40);delay=d.ms>40?Math.min(1000,2*d.ms):0;if(slow>2500){pause();message('高負荷で停止。格子サイズを下げてください / High load: reduce grid size.');}draw();};}timer=setTimeout(()=>{pause();message('応答待ち時間を超えました / Calculation timeout');},2000);worker.postMessage({a,n,p,mode:$('mode').value});}
function frame(t){if(!paused&&!busy&&!drag&&!document.hidden&&t-last>=Math.max(1000/+$('rate').value,delay)){last=t;request();}requestAnimationFrame(frame);}
$('play').onclick=()=>{if(paused){paused=false;slow=0;message('');sync();}else pause();draw();};$('step').onclick=()=>{pause();request();};$('reset').onclick=reset;$('preset').onchange=reset;$('resolution').onchange=reset;$('shuffle').onclick=()=>{$('seed').value=crypto.getRandomValues(new Uint32Array(1))[0];reset();};$('reference').onclick=()=>{cancel();p={...defaults};for(const k of keys)$(k).value=p[k];$('mode').value='discrete';reset();};$('mode').onchange=()=>{cancel();sync();};
for(const k of ids)$(k).oninput=()=>{if(keys.includes(k)){cancel();p[k]=+$(k).value;if(p.b1>=p.b2||p.d1>=p.d2){pause();message('下限は上限より小さくしてください / Lower thresholds must be below upper thresholds.');}else message('');}sync();};
function paint(e){const rect=c.getBoundingClientRect(),x=(e.clientX-rect.left-view.x)/view.size*n,y=(e.clientY-rect.top-view.y)/view.size*n;if(x<0||y<0||x>=n||y>=n)return;const radius=+$('brush').value;for(let j=-radius;j<=radius;j++)for(let i=-radius;i<=radius;i++){const w=Math.max(0,Math.min(1,radius+.5-Math.hypot(i,j))),index=((Math.floor(y)+j+n)%n)*n+(Math.floor(x)+i+n)%n;a[index]=erase?a[index]*(1-w):Math.max(a[index],w);}draw();}
c.onpointerdown=e=>{cancel();drag=true;erase=e.button===2||$('tool').value==='erase';c.setPointerCapture(e.pointerId);paint(e);};c.onpointermove=e=>{if(drag)paint(e);};c.onpointerup=c.onpointercancel=()=>{drag=false;};c.oncontextmenu=e=>e.preventDefault();
$('menuToggle').onclick=()=>{const v=$('sidebar').classList.toggle('open');$('sidebarBackdrop').classList.toggle('open',v);$('menuToggle').setAttribute('aria-expanded',v);};$('sidebarBackdrop').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');};addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{cancel();drag=false;last=0;});
$('save').onclick=()=>{pause();draw();const url=URL.createObjectURL(new Blob([JSON.stringify({format:'alife-smoothlife',version:1,n,values:Array.from(a),params:p,mode:$('mode').value,ticks})],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='smoothlife-'+Date.now()+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('保存しました / Saved');};
async function load(file){const id=++loadId;try{if(!file||file.size>3*1024*1024)throw Error();const d=JSON.parse(await file.text());if(id!==loadId)return;if(d.format!=='alife-smoothlife'||d.version!==1||![128,192,256].includes(d.n)||!Array.isArray(d.values)||d.values.length!==d.n*d.n||!d.values.every(v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1)||!['discrete','continuous'].includes(d.mode)||!Number.isSafeInteger(d.ticks)||d.ticks<0)throw Error();const params={};for(const k of keys){const v=d.params?.[k];if(typeof v!=='number'||!Number.isFinite(v)||v<+$(k).min||v>+$(k).max)throw Error();params[k]=v;}if(params.b1>=params.b2||params.d1>=params.d2)throw Error();pause();n=d.n;a=Float32Array.from(d.values);p=params;ticks=d.ticks;$('resolution').value=n;$('mode').value=d.mode;for(const k of keys)$(k).value=p[k];sync();draw();message('読み込みました / Loaded (paused)');}catch{if(id===loadId)message('不正なSmoothLifeファイルです。状態は保持 / Invalid file; state retained.');}}
$('open').onclick=()=>$('file').click();$('file').onchange=()=>{load($('file').files[0]);$('file').value='';};addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();if(e.dataTransfer.files.length===1)load(e.dataTransfer.files[0]);}});reset();requestAnimationFrame(frame);
