import {GENES,VERSION,STEPS,random,genome,body,step,center,edges} from './core.js';
const $=id=>document.getElementById(id),c=$('canvas'),ctx=c.getContext('2d');let pop=[],best=null,first=null,score=-Infinity,firstScore=0,gen=0,hist=[],running=false,busy=false,worker,timer,baseSeed=42,epoch=0,loadId=0,slow=0,nextAt=0,replaying=!matchMedia('(prefers-reduced-motion: reduce)').matches,bs=[body(),body()],replayStep=0,last=0,acc=0;
function message(s){$('notice').textContent=s;$('notice').hidden=!s;}
function sync(){$('play').textContent=running?'進化を停止 / Pause evolution':'進化を開始 / Start evolution';$('save').disabled=!best;$('replay').textContent=replaying?'再生を止める / Pause replay':'再生 / Replay';$('progress').textContent=`世代 / Generation ${gen} · ${busy?'評価中 / Evaluating': 'Ready'}${best?' · Best '+score.toFixed(3):''}`;}
function cancel(){epoch++;clearTimeout(timer);worker?.terminate();worker=null;busy=false;}
function stop(){running=false;cancel();sync();}
function replayReset(){bs=[body(),body()];replayStep=0;acc=0;}
function reset(){stop();baseSeed=+$('seed').value;if(!Number.isInteger(baseSeed)||baseSeed<0||baseSeed>4294967295){baseSeed=42;$('seed').value=42;}const rand=random(baseSeed);pop=Array.from({length:+$('population').value},()=>genome(rand));best=first=null;gen=0;hist=[];score=-Infinity;slow=0;message('');replayReset();sync();drawChart();draw();}
function request(){if(busy||document.hidden)return;busy=true;const token=epoch;worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>{stop();message('計算エラー。開始で再試行 / Worker error; retry Start.');};worker.onmessage=({data:d})=>{if(token!==epoch)return;clearTimeout(timer);worker.terminate();worker=null;busy=false;if(d.error){stop();message(d.error);return;}pop=d.pop;gen++;if(!first){first=d.best.slice();firstScore=d.score;}if(!best||d.score>score){best=d.best.slice();score=d.score;replayReset();}hist.push([d.score,d.mean]);if(hist.length>500)hist.shift();slow=d.ms>1000?slow+d.ms:Math.max(0,slow-500);nextAt=performance.now()+Math.max(200,d.ms);if(slow>5000){stop();message('高負荷で停止。集団サイズを下げてください / High load: reduce population.');}sync();drawChart();draw();};timer=setTimeout(()=>{stop();message('計算が応答しないため停止 / Evaluation timeout');},10000);worker.postMessage({pop,rate:+$('mutation').value,seed:(baseSeed+Math.imul(gen+1,2654435761))>>>0});sync();}
function draw(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height,scale=Math.min(75,w/6);for(let j=0;j<2;j++){const b=bs[j],ground=h*(j===0?.4:.73),cam=center(b)-.5;ctx.strokeStyle='#343d4d';ctx.beginPath();ctx.moveTo(0,ground);ctx.lineTo(w,ground);ctx.stroke();ctx.font='12px system-ui';ctx.fillStyle=j?'#5ad1c7':'#929aab';ctx.fillText(j?'最優秀 / Best':'初代 / First generation',16,ground-135);ctx.fillText(`${(center(b)-b.start).toFixed(2)} body widths`,16,ground+25);for(let k=Math.floor(cam-w/scale);k<cam+w/scale;k++){const x=w/2+(k-cam-.5)*scale;ctx.fillStyle='#444f61';ctx.fillRect(x,ground,1,6);ctx.fillText(String(k),x,ground+15);}const coords=b.p.map(p=>[w/2+(p.x-cam-.5)*scale,ground-p.y*scale]);ctx.strokeStyle=j?'#5ad1c7':'#929aab';ctx.lineWidth=4;for(const [a,b]of edges){ctx.beginPath();ctx.moveTo(...coords[a]);ctx.lineTo(...coords[b]);ctx.stroke();}for(const [x,y]of coords){ctx.fillStyle=j?'#a9fff3':'#d7deeb';ctx.beginPath();ctx.arc(x,y,7,0,7);ctx.fill();}}$('stats').textContent=`${best?'Replay':'Start evolution to generate a controller'} · ${(replayStep/120).toFixed(1)} / 6.0 s`;}
function drawChart(){const c=$('chart'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!hist.length)return;let lo=Math.min(0,...hist.flat()),hi=Math.max(.1,...hist.flat());for(let j=1;j>=0;j--){x.strokeStyle=j?'#939aab':'#5ad1c7';x.beginPath();hist.forEach((v,i)=>{const px=8+i/Math.max(1,hist.length-1)*264,py=115-(v[j]-lo)/(hi-lo)*100;i?x.lineTo(px,py):x.moveTo(px,py);});x.stroke();}x.fillStyle='#939aab';x.font='11px system-ui';x.fillText(hi.toFixed(2),4,11);}
function frame(t){const dt=Math.min(100,t-last);last=t;if(!document.hidden){if(running&&!busy&&t>=nextAt)request();if(replaying&&best){acc+=dt;let k=0;while(acc>=1000/120&&k++<12){step(bs[0],first);step(bs[1],best);acc-=1000/120;replayStep++;if(replayStep>=STEPS){replayReset();break;}}draw();}}requestAnimationFrame(frame);}
$('play').onclick=()=>{if(running)stop();else{running=true;slow=0;message('');sync();}};$('step').onclick=()=>{stop();request();};$('reset').onclick=reset;$('population').onchange=reset;$('mutation').oninput=()=>$('mutationVal').value=(+$('mutation').value).toFixed(2);$('replay').onclick=()=>{replaying=!replaying;acc=0;sync();};
$('menuToggle').onclick=()=>{const v=$('sidebar').classList.toggle('open');$('sidebarBackdrop').classList.toggle('open',v);$('menuToggle').setAttribute('aria-expanded',v);};$('sidebarBackdrop').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open');$('menuToggle').setAttribute('aria-expanded','false');};addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{cancel();acc=0;sync();});
$('save').onclick=()=>{if(!best)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'alife-neuroevolution',version:1,physics:VERSION,genome:best,baseline:first,generation:gen,score,firstScore})],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='evolved-creature-'+gen+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function load(file){const id=++loadId;try{if(!file||file.size>100000)throw Error();const d=JSON.parse(await file.text());if(id!==loadId)return;const valid=g=>Array.isArray(g)&&g.length===GENES&&g.every(v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=5);if(d.format!=='alife-neuroevolution'||d.version!==1||d.physics!==VERSION||!valid(d.genome)||!valid(d.baseline))throw Error();const {evaluate}=await import('./core.js');if(id!==loadId)return;const fitness=evaluate(d.genome),baselineFitness=evaluate(d.baseline);stop();best=d.genome.slice();first=d.baseline.slice();score=fitness;firstScore=baselineFitness;gen=0;hist=[];pop=Array.from({length:+$('population').value},()=>best.slice());slow=0;replayReset();sync();drawChart();draw();message('個体を復元。開始でこの脳から進化 / Loaded. Start evolves from this brain.');}catch{if(id===loadId)message('対応する個体ファイルではありません / Invalid creature; state retained.');}}
$('open').onclick=()=>$('file').click();$('file').onchange=()=>{load($('file').files[0]);$('file').value='';};addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();if(e.dataTransfer.files.length===1)load(e.dataTransfer.files[0]);}});reset();requestAnimationFrame(frame);
