export const VERSION='spring-creature-v1',GENES=158,STEPS=720;
export const edges=[[0,1],[1,2],[2,3],[3,0],[0,2],[1,3]],base=[[0,.8],[1,.8],[1,1.6],[0,1.6]],lengths=edges.map(([i,j])=>Math.hypot(base[i][0]-base[j][0],base[i][1]-base[j][1]));
export function random(seed){let s=seed>>>0;return ()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
export function genome(rand){return Array.from({length:GENES},()=>2*rand()-1);}
export function body(){const b={p:base.map(([x,y])=>({x,y,vx:0,vy:0})),t:0};for(let i=0;i<120;i++)step(b,null);b.t=0;b.start=center(b);return b;}
export function center(b){return b.p.reduce((s,p)=>s+p.x,0)/4;}
export function brain(b,g){const input=[Math.sin(b.t*2*Math.PI),Math.cos(b.t*2*Math.PI),...edges.map(([i,j],k)=>Math.hypot(b.p[i].x-b.p[j].x,b.p[i].y-b.p[j].y)/lengths[k]-1),...b.p.map(p=>p.y<=.101?1:0)];let q=0;const h=[];for(let i=0;i<8;i++){let s=g[q++];for(const v of input)s+=g[q++]*v;h.push(Math.tanh(s));}const out=[];for(let i=0;i<6;i++){let s=g[q++];for(const v of h)s+=g[q++]*v;out.push(Math.tanh(s));}return out;}
export function step(b,g){const dt=1/120,act=g?brain(b,g):[0,0,0,0,0,0],f=b.p.map(()=>[0,-9.8]);for(let k=0;k<6;k++){const [i,j]=edges[k],a=b.p[i],c=b.p[j],dx=c.x-a.x,dy=c.y-a.y,d=Math.max(1e-6,Math.hypot(dx,dy)),ux=dx/d,uy=dy/d;const force=90*(d-lengths[k]*(1+.25*act[k]))+3*((c.vx-a.vx)*ux+(c.vy-a.vy)*uy);f[i][0]+=force*ux;f[i][1]+=force*uy;f[j][0]-=force*ux;f[j][1]-=force*uy;}
 for(let i=0;i<4;i++){const p=b.p[i];p.vx=(p.vx+dt*f[i][0])*.999;p.vy=(p.vy+dt*f[i][1])*.999;p.x+=dt*p.vx;p.y+=dt*p.vy;if(p.y<.1){p.y=.1;p.vy=Math.max(0,p.vy);p.vx*=.8;}if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||Math.abs(p.x)>1000||p.y>100)throw Error('Physics limit');}b.t+=dt;}
export function evaluate(g){const b=body();for(let i=0;i<STEPS;i++)step(b,g);return center(b)-b.start;}
export function generation(pop,rate,seed){const rand=random(seed),rank=pop.map(g=>({g,score:evaluate(g)})).sort((a,b)=>b.score-a.score),next=rank.slice(0,2).map(x=>x.g.slice());const parent=()=>{let best=rank[Math.floor(rand()*rank.length)];for(let i=0;i<2;i++){const c=rank[Math.floor(rand()*rank.length)];if(c.score>best.score)best=c;}return best.g;};while(next.length<pop.length){const a=parent(),b=parent();next.push(a.map((v,i)=>{let x=rand()<.5?v:b[i];if(rand()<rate)x+=(rand()+rand()+rand()-1.5)*.5;return Math.max(-5,Math.min(5,x));}));}return {pop:next,best:rank[0].g,score:rank[0].score,mean:rank.reduce((s,x)=>s+x.score,0)/rank.length};}
